<a href="https://colab.research.google.com/github/AmanRajput997/Next-Word-Predictor-Using-LSTM/blob/main/Next_Word_Predictor_Using_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
dataset ="""At the World’s Parliament of Religions, Chicago, 11 September 1893

Sisters and Brothers of America,

It fills my heart with joy unspeakable to rise in response to the warm and cordial welcome which you have given us.
I thank you in the name of the most ancient order of monks in the world;
I thank you in the name of the mother of religions;
and I thank you in the name of the millions and millions of Hindu people of all classes and sects
My thanks, also, to some of the speakers on this platform who, referring to the delegates from the Orient, have told you that these men from far-off nations may well claim the honour of bearing to different lands the idea of toleration.
I am proud to belong to a religion which has taught the world both tolerance and universal acceptance.
We believe not only in universal toleration, but we accept all religions as true.
I am proud to belong to a nation which has sheltered the persecuted and the refugees of all religions and all nations of the earth.
I am proud to tell you that we have gathered in our bosom the purest remnant of the Israelites, who came to southern India and took refuge with us in the very year in which their holy temple was shattered to pieces by Roman tyranny.
I am proud to belong to the religion which has sheltered and is still fostering the remnant of the grand Zoroastrian nation.
I will quote to you, brethren, a few lines from a hymn which I remember to have repeated from my earliest boyhood, which is every day repeated by millions of human beings:
‘As the different streams having their sources in different places all mingle their water in the sea, so, O Lord, the different paths which men take through different tendencies, various though they appear, crooked or straight, all lead to Thee.’

The present convention, which is one of the most august assemblies ever held, is in itself a vindication, a declaration to the world, of the wonderful doctrine preached in the Gita: ‘Whosoever comes to Me, through whatsoever form, I reach him;
all men are struggling through paths which in the end lead to Me.’
Sectarianism, bigotry, and its horrible descendant, fanaticism, have long possessed this beautiful earth.
They have filled the earth with violence, drenched it often and often with human blood, destroyed civilization, and sent whole nations to despair.
Had it not been for these horrible demons, human society would be far more advanced than it is now.
But their time is come; and I fervently hope that the bell that tolled this morning in honour of this convention may be the death-knell of all fanaticism, of all persecutions with the sword or with the pen, and of all uncharitable feelings between persons wending their way to the same goal."""

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts([dataset])

In [ ]:
tokenizer.word_index

{'the': 1,
 'of': 2,
 'to': 3,
 'and': 4,
 'in': 5,
 'i': 6,
 'which': 7,
 'all': 8,
 'you': 9,
 'with': 10,
 'have': 11,
 'a': 12,
 'is': 13,
 'different': 14,
 'their': 15,
 'religions': 16,
 'it': 17,
 'this': 18,
 'from': 19,
 'that': 20,
 'am': 21,
 'proud': 22,
 'my': 23,
 'thank': 24,
 'name': 25,
 'world': 26,
 'millions': 27,
 'men': 28,
 'nations': 29,
 'belong': 30,
 'has': 31,
 'we': 32,
 'earth': 33,
 'human': 34,
 'through': 35,
 'us': 36,
 'most': 37,
 'who': 38,
 'these': 39,
 'far': 40,
 'may': 41,
 'honour': 42,
 'toleration': 43,
 'religion': 44,
 'universal': 45,
 'not': 46,
 'but': 47,
 'nation': 48,
 'sheltered': 49,
 'remnant': 50,
 'by': 51,
 'repeated': 52,
 'paths': 53,
 'they': 54,
 'or': 55,
 'lead': 56,
 '’': 57,
 'convention': 58,
 'me': 59,
 'horrible': 60,
 'fanaticism': 61,
 'often': 62,
 'be': 63,
 'at': 64,
 'world’s': 65,
 'parliament': 66,
 'chicago': 67,
 '11': 68,
 'september': 69,
 '1893': 70,
 'sisters': 71,
 'brothers': 72,
 'america': 73,
 'fi

In [ ]:
len(tokenizer.word_index)

241

In [ ]:
for sentence in dataset.split('\n'):
  print(sentence)

At the World’s Parliament of Religions, Chicago, 11 September 1893

Sisters and Brothers of America,

It fills my heart with joy unspeakable to rise in response to the warm and cordial welcome which you have given us.
I thank you in the name of the most ancient order of monks in the world;
I thank you in the name of the mother of religions;
and I thank you in the name of the millions and millions of Hindu people of all classes and sects
My thanks, also, to some of the speakers on this platform who, referring to the delegates from the Orient, have told you that these men from far-off nations may well claim the honour of bearing to different lands the idea of toleration.
I am proud to belong to a religion which has taught the world both tolerance and universal acceptance.
We believe not only in universal toleration, but we accept all religions as true.
I am proud to belong to a nation which has sheltered the persecuted and the refugees of all religions and all nations of the earth.
I am 

In [ ]:
for sentence in dataset.split('\n'):
  print(tokenizer.texts_to_sequences([sentence]))

[[64, 1, 65, 66, 2, 16, 67, 68, 69, 70]]
[[]]
[[71, 4, 72, 2, 73]]
[[]]
[[17, 74, 23, 75, 10, 76, 77, 3, 78, 5, 79, 3, 1, 80, 4, 81, 82, 7, 9, 11, 83, 36]]
[[6, 24, 9, 5, 1, 25, 2, 1, 37, 84, 85, 2, 86, 5, 1, 26]]
[[6, 24, 9, 5, 1, 25, 2, 1, 87, 2, 16]]
[[4, 6, 24, 9, 5, 1, 25, 2, 1, 27, 4, 27, 2, 88, 89, 2, 8, 90, 4, 91]]
[[23, 92, 93, 3, 94, 2, 1, 95, 96, 18, 97, 38, 98, 3, 1, 99, 19, 1, 100, 11, 101, 9, 20, 39, 28, 19, 40, 102, 29, 41, 103, 104, 1, 42, 2, 105, 3, 14, 106, 1, 107, 2, 43]]
[[6, 21, 22, 3, 30, 3, 12, 44, 7, 31, 108, 1, 26, 109, 110, 4, 45, 111]]
[[32, 112, 46, 113, 5, 45, 43, 47, 32, 114, 8, 16, 115, 116]]
[[6, 21, 22, 3, 30, 3, 12, 48, 7, 31, 49, 1, 117, 4, 1, 118, 2, 8, 16, 4, 8, 29, 2, 1, 33]]
[[6, 21, 22, 3, 119, 9, 20, 32, 11, 120, 5, 121, 122, 1, 123, 50, 2, 1, 124, 38, 125, 3, 126, 127, 4, 128, 129, 10, 36, 5, 1, 130, 131, 5, 7, 15, 132, 133, 134, 135, 3, 136, 51, 137, 138]]
[[6, 21, 22, 3, 30, 3, 1, 44, 7, 31, 49, 4, 13, 139, 140, 1, 50, 2, 1, 141, 142, 48]]
[[

In [ ]:
for sentence in dataset.split('\n'):
  print(tokenizer.texts_to_sequences([sentence])[0])

[64, 1, 65, 66, 2, 16, 67, 68, 69, 70]
[]
[71, 4, 72, 2, 73]
[]
[17, 74, 23, 75, 10, 76, 77, 3, 78, 5, 79, 3, 1, 80, 4, 81, 82, 7, 9, 11, 83, 36]
[6, 24, 9, 5, 1, 25, 2, 1, 37, 84, 85, 2, 86, 5, 1, 26]
[6, 24, 9, 5, 1, 25, 2, 1, 87, 2, 16]
[4, 6, 24, 9, 5, 1, 25, 2, 1, 27, 4, 27, 2, 88, 89, 2, 8, 90, 4, 91]
[23, 92, 93, 3, 94, 2, 1, 95, 96, 18, 97, 38, 98, 3, 1, 99, 19, 1, 100, 11, 101, 9, 20, 39, 28, 19, 40, 102, 29, 41, 103, 104, 1, 42, 2, 105, 3, 14, 106, 1, 107, 2, 43]
[6, 21, 22, 3, 30, 3, 12, 44, 7, 31, 108, 1, 26, 109, 110, 4, 45, 111]
[32, 112, 46, 113, 5, 45, 43, 47, 32, 114, 8, 16, 115, 116]
[6, 21, 22, 3, 30, 3, 12, 48, 7, 31, 49, 1, 117, 4, 1, 118, 2, 8, 16, 4, 8, 29, 2, 1, 33]
[6, 21, 22, 3, 119, 9, 20, 32, 11, 120, 5, 121, 122, 1, 123, 50, 2, 1, 124, 38, 125, 3, 126, 127, 4, 128, 129, 10, 36, 5, 1, 130, 131, 5, 7, 15, 132, 133, 134, 135, 3, 136, 51, 137, 138]
[6, 21, 22, 3, 30, 3, 1, 44, 7, 31, 49, 4, 13, 139, 140, 1, 50, 2, 1, 141, 142, 48]
[6, 143, 144, 3, 9, 145, 12, 1

In [ ]:
input_sequences = []
for sentence in dataset.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1, len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])


In [ ]:
input_sequences

[[64, 1],
 [64, 1, 65],
 [64, 1, 65, 66],
 [64, 1, 65, 66, 2],
 [64, 1, 65, 66, 2, 16],
 [64, 1, 65, 66, 2, 16, 67],
 [64, 1, 65, 66, 2, 16, 67, 68],
 [64, 1, 65, 66, 2, 16, 67, 68, 69],
 [64, 1, 65, 66, 2, 16, 67, 68, 69, 70],
 [71, 4],
 [71, 4, 72],
 [71, 4, 72, 2],
 [71, 4, 72, 2, 73],
 [17, 74],
 [17, 74, 23],
 [17, 74, 23, 75],
 [17, 74, 23, 75, 10],
 [17, 74, 23, 75, 10, 76],
 [17, 74, 23, 75, 10, 76, 77],
 [17, 74, 23, 75, 10, 76, 77, 3],
 [17, 74, 23, 75, 10, 76, 77, 3, 78],
 [17, 74, 23, 75, 10, 76, 77, 3, 78, 5],
 [17, 74, 23, 75, 10, 76, 77, 3, 78, 5, 79],
 [17, 74, 23, 75, 10, 76, 77, 3, 78, 5, 79, 3],
 [17, 74, 23, 75, 10, 76, 77, 3, 78, 5, 79, 3, 1],
 [17, 74, 23, 75, 10, 76, 77, 3, 78, 5, 79, 3, 1, 80],
 [17, 74, 23, 75, 10, 76, 77, 3, 78, 5, 79, 3, 1, 80, 4],
 [17, 74, 23, 75, 10, 76, 77, 3, 78, 5, 79, 3, 1, 80, 4, 81],
 [17, 74, 23, 75, 10, 76, 77, 3, 78, 5, 79, 3, 1, 80, 4, 81, 82],
 [17, 74, 23, 75, 10, 76, 77, 3, 78, 5, 79, 3, 1, 80, 4, 81, 82, 7],
 [17, 74, 23, 75,

In [ ]:
[len(x) for x in input_sequences]

[2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 2,
 3,
 4,
 5,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,

In [ ]:
max([len(x) for x in input_sequences])

53

In [ ]:
max_len = max([len(x) for x in input_sequences])

In [ ]:
from tensorflow.keras.utils import pad_sequences
pad_sequences(input_sequences, maxlen = max_len, padding = 'pre')

array([[  0,   0,   0, ...,   0,  64,   1],
       [  0,   0,   0, ...,  64,   1,  65],
       [  0,   0,   0, ...,   1,  65,  66],
       ...,
       [  0,   0,  47, ..., 239,   3,   1],
       [  0,  47,  15, ...,   3,   1, 240],
       [ 47,  15, 222, ...,   1, 240, 241]], dtype=int32)

In [ ]:
from tensorflow.keras.utils import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding = 'pre')

In [ ]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,  64,   1],
       [  0,   0,   0, ...,  64,   1,  65],
       [  0,   0,   0, ...,   1,  65,  66],
       ...,
       [  0,   0,  47, ..., 239,   3,   1],
       [  0,  47,  15, ...,   3,   1, 240],
       [ 47,  15, 222, ...,   1, 240, 241]], dtype=int32)

In [ ]:
padded_input_sequences[:,:-1]

array([[  0,   0,   0, ...,   0,   0,  64],
       [  0,   0,   0, ...,   0,  64,   1],
       [  0,   0,   0, ...,  64,   1,  65],
       ...,
       [  0,   0,  47, ...,  15, 239,   3],
       [  0,  47,  15, ..., 239,   3,   1],
       [ 47,  15, 222, ...,   3,   1, 240]], dtype=int32)

In [ ]:
x = padded_input_sequences[:,:-1]

In [ ]:
padded_input_sequences[:,-1]

array([  1,  65,  66,   2,  16,  67,  68,  69,  70,   4,  72,   2,  73,
        74,  23,  75,  10,  76,  77,   3,  78,   5,  79,   3,   1,  80,
         4,  81,  82,   7,   9,  11,  83,  36,  24,   9,   5,   1,  25,
         2,   1,  37,  84,  85,   2,  86,   5,   1,  26,  24,   9,   5,
         1,  25,   2,   1,  87,   2,  16,   6,  24,   9,   5,   1,  25,
         2,   1,  27,   4,  27,   2,  88,  89,   2,   8,  90,   4,  91,
        92,  93,   3,  94,   2,   1,  95,  96,  18,  97,  38,  98,   3,
         1,  99,  19,   1, 100,  11, 101,   9,  20,  39,  28,  19,  40,
       102,  29,  41, 103, 104,   1,  42,   2, 105,   3,  14, 106,   1,
       107,   2,  43,  21,  22,   3,  30,   3,  12,  44,   7,  31, 108,
         1,  26, 109, 110,   4,  45, 111, 112,  46, 113,   5,  45,  43,
        47,  32, 114,   8,  16, 115, 116,  21,  22,   3,  30,   3,  12,
        48,   7,  31,  49,   1, 117,   4,   1, 118,   2,   8,  16,   4,
         8,  29,   2,   1,  33,  21,  22,   3, 119,   9,  20,  3

In [ ]:
y = padded_input_sequences[:,-1]

In [ ]:
x.shape

(467, 52)

In [ ]:
y.shape

(467,)

In [ ]:
from tensorflow.keras.utils import to_categorical
to_categorical(y,num_classes=242)

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=242)

In [ ]:
y.shape

(467, 242)

In [ ]:
y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

LSTM Architecture design

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [ ]:
model = Sequential ()

model.add(Embedding(242, 100, input_shape=(max_len-1,)))
model.add(LSTM(150))
model.add(Dense(242, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 52, 100)        │        24,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 242)            │        36,542 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 211,342 (825.55 KB)

 Trainable params: 211,342 (825.55 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(x,y,epochs=100)

Epoch 1/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 2s 52ms/step - accuracy: 0.0454 - loss: 5.4504
Epoch 2/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 51ms/step - accuracy: 0.0759 - loss: 5.0745
Epoch 3/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 2s 76ms/step - accuracy: 0.0761 - loss: 4.9695
Epoch 4/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - accuracy: 0.0804 - loss: 4.8947
Epoch 5/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.0760 - loss: 4.9608
Epoch 6/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - accuracy: 0.0863 - loss: 4.8814
Epoch 7/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 52ms/step - accuracy: 0.0866 - loss: 4.8131
Epoch 8/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.0867 - loss: 4.8039
Epoch 9/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.0758 - loss: 4.7168
Epoch 10/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step - accuracy: 0.0934 - loss: 4.5160
Epoch 11/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.0979 - loss: 4.5439
Epoch 12/100
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step

In [ ]:
import numpy as np

In [71]:
import time
text = "heart"

for i in range(5):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]

  # padding
  padded_token_text = pad_sequences([token_text], maxlen = max_len, padding='pre')

  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word, index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
heart the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
heart the world’s
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
heart the world’s parliament
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
heart the world’s parliament of
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
heart the world’s parliament of religions
